### ISSUE TITLE
🖐Smart Maps Meetup Monthly: Presenter Ideas

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#159] opened 2023-05-22 05:31 UTC
### Purpose

The Smart Maps International Meetup template (#129) suggests we have a guest speaker for each meet up.

Let's list below some potential speakers, topics, or themes!

- [x] MUNDO/GeoAI (@yuiseki)
- [ ] OpenDroneMap (@mapconcierge ?)

**Comment by hfu** [comment] 2023-05-23 06:03
- [ ] Charites (@miya0001)? as in #114

**Comment by hfu** [comment] 2023-05-26 01:14
- [ ] @miya0001 on 高松スマートマップ (Takamatsu Smart Maps) - which seems to be really nice application of vector tiles.

**Comment by hfu** [comment] 2023-05-26 05:12
- [ ] @keichan34 on his products.

**Comment by hfu** [comment] 2023-06-01 00:06
I am working on planning / preparation for the June meetup.

**Comment by albertkun** [comment] 2023-06-01 04:22
@hfu  was a decision made on the next topic in #161 ? We can update the details if so!

**Comment by hfu** [comment] 2023-06-01 12:58
@albertkun Thank you for the question. Yes, we discussed and I am currently trying to find the speaker who do the presentation. I quickly drafted the agenda: 

# Smart Maps Meetup Pacific 3

## Opening

Introduction by Hidenori, Smart Maps Lead (5 min)
Introduction by new participants (5 min)

## Presentation

*** by *** (15 min)

## Closing - next actions

Introduction of upcoming events (5 min)
Discussions (10 min)
How to keep in touch (2 min)


What do you think? Is there anything we can add or delete?

**Comment by hfu** [comment] 2023-06-02 03:54
We have @ShogoHirasawa on UNVT Portable for Smart Maps Meetup Pacific 3! 

## Presentation

UNVT Portable by Shogo (15 min)

**Comment by albertkun** [comment] 2023-06-02 09:36
@hfu exciting!! I'll go ahead and update this over the weekend! UN VT is a good entry point for the Smart Maps Group so that's excellent!

**Comment by hfu** [comment] 2023-06-03 22:41
Let's discuss who we should invite as a guest presenter in the Pacific 4 in July.

**Comment by hfu** [comment] 2023-06-11 11:08
As discussed in #171, let's make sure that we are using the name "Meetup Monthly" rather than "Meetup Pacific". 

I am writing the invitation as a separate `DocumentationSeed` issue. 👋🏻

**Comment by hfu** [comment] 2023-06-12 13:06
@albertkun I confirmed the change on the Documentation web site. Thanks you so much!

**Comment by hfu** [comment] 2023-07-16 11:24
今後、月例の流れの中で考えていくことにしましょう。

**Closed by hfu** 2023-07-16 11:24 UTC
Labels: priority/SHOULD
